services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: camara_backend
    environment:
      # Agora esta configuração está correta porque o nome do contêiner é 'postgres'
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/camara_db
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - camara-network
    command: >
      sh -c "sleep 5 && python main.py"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: camara_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - camara-network
    environment:
      - VITE_API_URL=http://localhost:8000

networks:
  camara-network:
    external: true