services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: camara_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/camara_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - camara-network
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python main.py"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: camara_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - camara-network
    environment:
      - VITE_API_URL=http://localhost:8000

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: camara_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data          # Volume persistente
      - ./camara.sql:/docker-entrypoint-initdb.d/camara.sql  # Script de inicialização
    networks:
      - camara-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15

networks:
  camara-network:
    driver: bridge

volumes:
  pgdata: {}
